language: node_js
node_js:
  - "node"

cache: npm

install: npm install
script: npm run build

deploy:
  provider: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist
  on:
    branch: dev