language: node_js
node_js:
  - lts/*

cache: npm

install: npm install
script: 
  - npm run build
  - echo 'clipfetcher.com' > dist/CNAME

deploy:
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: dev