language: node_js
node_js:
  - "node"

cache: npm

install: npm install
script: npm run build

deploy:
  commit_message: Deploy From Travis-CI
  target_branch: master
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: dev